Update unicode handling for new svn
Fix error in request_unstage:
     AttributeError: 'str' object has no attribute 'decode'

Looks like dsoprea/PySvn@cf15fbcb5b3cf89ef393ba378dbade4276a2b394 made
subprocess decode output unless we're asking for binary. cat() asks for
binary so needed to decode makes sense, but when request_unstage calls
run_command it does not.